run-tests:
	@ cargo test

open-docs:
	@ cargo doc --open

check-format:
	@ cargo fmt --all -- --check

code-format:
	@ cargo fmt --all

publish-dry-run:
	@ cargo publish --dry-run

publish:
	@ cargo publish

clippy-pedantic:
	@ ./bin/clippy-pedantic.sh

generate-report:
	@ ./bin/coverage-report.sh --open